// <auto-generated />
using System;
using CyclingForge.Modules.Garmin.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyclingForge.Modules.Garmin.Infrastructure.Migrations
{
    [DbContext(typeof(GarminDbContext))]
    partial class GarminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("garmin")
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyclingForge.Modules.Garmin.Domain.Entities.GarminDailyWellness", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AverageStressLevel")
                        .HasColumnType("int");

                    b.Property<int?>("BodyBatteryMax")
                        .HasColumnType("int");

                    b.Property<int?>("BodyBatteryMin")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("StepsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingReadinessLevel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("TrainingReadinessScore")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<float?>("Vo2MaxMlPerMinPerKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyWellness", "garmin");
                });

            modelBuilder.Entity("CyclingForge.Modules.Garmin.Domain.Entities.GarminSleepData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("AverageRespirationRate")
                        .HasColumnType("real");

                    b.Property<float?>("AverageSpO2")
                        .HasColumnType("real");

                    b.Property<int>("AwakeSeconds")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DeepSleepSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LightSleepSeconds")
                        .HasColumnType("int");

                    b.Property<int>("RemSleepSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SleepEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SleepStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSleepSeconds")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("SleepData", "garmin");
                });

            modelBuilder.Entity("CyclingForge.Modules.Garmin.Domain.Entities.GarminToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TokenSecret")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tokens", "garmin");
                });
#pragma warning restore 612, 618
        }
    }
}
