// <auto-generated />
using System;
using CyclingForge.Modules.Activities.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyclingForge.Modules.Activities.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ActivitiesDbContext))]
    [Migration("20260216100000_AddBest20MinPower")]
    partial class AddBest20MinPower
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("activities")
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyclingForge.Modules.Activities.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("AverageHeartRate")
                        .HasColumnType("real");

                    b.Property<float?>("AveragePower")
                        .HasColumnType("real");

                    b.Property<float?>("Best20MinPower")
                        .HasColumnType("real");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("int");

                    b.Property<float?>("IntensityFactor")
                        .HasColumnType("real");

                    b.Property<float?>("MaxHeartRate")
                        .HasColumnType("real");

                    b.Property<float?>("MaxPower")
                        .HasColumnType("real");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("real");

                    b.Property<int>("MovingTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<float?>("NormalizedPower")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalElevationGain")
                        .HasColumnType("real");

                    b.Property<float?>("TrainingStressScore")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("StravaActivityId", "UserId")
                        .IsUnique();

                    b.ToTable("Activities", "activities");
                });
#pragma warning restore 612, 618
        }
    }
}
